title:            Sudev Ambadi 
tagline:          Free thinker
description:      Sudev Ambadi's personal blog.
# Your site's domain goes here. Leave localhost server or blank when working locally.
#url:              http://localhost:4000
url:             http://sudev.github.io

# Owner/author information
owner:
  name:           Sudev Ambadi
  avatar:         dp.jpg
#  bio:            "Free and Open software || <br /> operating systems ||   <br /> cloud computing  ||  <br /> programming ||  <br /> cricket ||  <br /> traveller ||  <br /> careless"
# bio:      "<strong>I &#9829;</strong> <br /> &#8594; Free and Open software <br /> &#8674; operating systems, cloud computing, programming and cricket. Currently doing my B Tech in Computer science and Engineering at National Institute of Technology, Calicut."
  bio:      "I'm a computer enthusiast interested in exploring Free and Open software, operating systems, cloud computing, programming and cricket. "
  email:    sudevdev@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:  sudev        
  facebook: sudev.ambadi       
  github: sudev        
  linkedin:       
  instagram: sudev_ambadi      
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-39443594-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        
# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Articles
    url: /articles/
  - title: Travel
    url: /travel/

#  - title: Theme Setup
#   url: /theme-setup/
  - title: Old blog
    url: http://sudevshares.blogspot.in
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkata
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
