markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Sudev Ambadi 
url: http://sudev.github.com
description: My findings may not amuse you
twitter: sudev
github: sudev
gravatar_url: https://fbcdn-sphotos-d-a.akamaihd.net/hphotos-ak-ash3/579631_4684343501374_1249882803_n.jpg 
